### ISSUE TITLE
Error when Time.zone is nil

### ISSUE THREAD

**Issue by ebeigarts** [collectiveidea/delayed_job#50]
Everything worked fine with 1.8.4.

@@@
    >> ActiveRecord::Base.default_timezone
    => :local
    >> Time.zone
    => nil

```
undefined method `now' for nil:NilClass (NoMethodError)
delayed_job-1.8.5/lib/delayed/job.rb:270:in `db_time_now'
```
