### ISSUE TITLE
undefined method for <Class> in ruby 1.9.2

### ISSUE THREAD

**Issue by sradu** [collectiveidea/delayed_job#293]
I'm porting an app from ruby 1.8.7 to ruby 1.9.2.

Delayed_Job doesn't seem to work, it fails with:
|  3 |        0 |        5 | --- !ruby/struct:Delayed::PerformableMethod 
object: !ruby/object:Class ClickShortTerm
method_name: :from_original
args: 
- 4e7217c48973561514000001
  | {undefined method `from_original' for #Class:0x007f813ce53ef8

ClickShortTerm has a from_original method, and it's accessible. Same setup worked on 1.8.7.

Using latest dj gem.
