### ISSUE TITLE
Don't guess the right backend in 2.0.6

### ISSUE THREAD

**Issue by mcollina** [collectiveidea/delayed_job#196]
I'm using DJ 2.0.6 and rails 2.3.10.
With the configuration that worked fine with DJ 2.0.5, I got the following error when starting a worker:

```
$ ./script/delayed_job start
/home/matteo/.rvm/gems/ruby-1.8.7-p330@livellocasa/gems/activesupport-2.3.10/lib/active_support/whiny_nil.rb:52:in `method_missing': undefined method `before_fork' for nil:NilClass (NoMethodError)
    from /home/matteo/.rvm/gems/ruby-1.8.7-p330@livellocasa/gems/delayed_job-2.0.6/lib/delayed/command.rb:55:in `daemonize'
    from ./script/delayed_job:12
```

After digging the stacktrace, I've solved my problem adding the following line to to my config/initializers/delayed_job_config.rb: `Delayed::Worker.backend = :active_record`.
Obiouvsly that's just a quick workaround.
